# Generated by Django 5.1.2 on 2024-10-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
                ('image', models.ImageField(upload_to='book_image/')),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=221)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
